name: "Build: "

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18.0.0+36
      uses: actions/setup-java@v3
      with:
        java-version: '18.0.0+36'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        mvn -B package --file pom.xml
        mkdir staging && cp target/*.jar staging
      
    - name: Get JAR Artifacts 
      uses: actions/upload-artifact@v3
      with:
        name: jar-artifacts
        path: staging
        
#     - name: Generate JavaDoc
#       run: |
#         mvn javadoc:javadoc
#         mkdir docs && cp -r target/site/apidocs/* docs
#     - name: Get JavaDoc Artifacts 
#       uses: actions/upload-artifact@v3
#       with:
#         name: doc-artifacts
#         path: docs
